# generated by datamodel-codegen:
#   filename:  resume.json
#   timestamp: 2025-04-09T19:15:44+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Contact(BaseModel):
    phone: str
    email: str
    github: str
    linkedin: str


class ExperienceItem(BaseModel):
    company: str
    location: str
    title: str
    dates: str
    responsibilities: List[str]


class Skills(BaseModel):
    languages: List[str]
    security: List[str]
    web_servers: List[str]
    web_frameworks: List[str]
    databases: List[str]
    os_platform: List[str]
    vm_containers_cloud: List[str]
    robotics: List[str]
    robotics_projects: List[str]


class Resume(BaseModel):
    name: str
    contact: Contact
    objective: str
    experience: List[ExperienceItem]
    skills: Skills
