name: Test Runner

on:
  push:
    branches [ "dev" ]
  pull_request:
    branches [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Install dependancies
      - run: pip install -r requirements.txt

      - name: Run tests
      - run: pytest


